//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class VictoryOnEight : IVictory
{
	public VictoryOnEight ()
	{

	}

	public bool checkVictory(grid g)
	{
		for(int x = 0; x < g.grid_size; ++x)
		{
			for(int y = 0; y < g.grid_size; ++y)
			{
				if(g.m_grid[y,x] == 8)
				{
					return true;
				}
			}
		}
		
		return false;
	}
}


